### ISSUE TITLE
pre-commit hooks for Markdown and/or ReStructured text

### ISSUE THREAD

**Issue by bourque** [lasp/developer-guide#27]
Perhaps there are some pre-commit hooks out there that check for mistakes in Markdown and ReStructured Text files that could help us out here

**Comment by bourque** [comment]
Suggestions from ChatGPT:

- https://github.com/iggyc/markdownlint
- https://github.com/prettier/prettier

and checking for empty files:

```
-   repo: local
    hooks:
    -   id: check-empty-files
        name: Check for Empty Files
        entry: bash -c 'if [ ! -s "$1" ]; then echo "Empty file: $1" && exit 1; fi' --
        language: system
        types: [text]
```
